name: Build

on:
  push:
    branches:
    tags:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew :library:build :app:buildDebug

